name: Building GSI..

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://artchen-my.sharepoint.cn/personal/chenxy_artchen_partner_onmschina_cn/_layouts/15/download.aspx?UniqueId=8c6162de-cb8a-496d-a915-9f42818d8f22&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvYXJ0Y2hlbi1teS5zaGFyZXBvaW50LmNuQDIwOTkwYmYyLTdhM2QtNGU5My1hNWQ3LWRhNjliYTIwMjI1ZSIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2MTAxNzA4MjMiLCJleHAiOiIxNjEwMTc0NDIzIiwiZW5kcG9pbnR1cmwiOiJ1U0Z5MlUwVnBJM3k0Y09wSDU1WHdCWnNuREJ2OVBSL1BoVno3eGptQS9jPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTY1IiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJNVFE0TldWak9UQXRaR1ptTVMwME5XRTBMV0ZqWTJRdE9ERmlNMlpoTjJZNFpqaGoiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiWkdOak9ETTFaR1F0WkRKbFl5MDBOR1JpTFRobU5tVXRObVEzWWpka05HSmtaall4IiwiYXBwX2Rpc3BsYXluYW1lIjoiT25lRHJpdmUgZm9yIEFQSSIsImFwcGlkIjoiZGZlMzZlNjAtNjEzMy00OGNmLTg2OWYtNGQxNWI4MzU0NzY5IiwidGlkIjoiMjA5OTBiZjItN2EzZC00ZTkzLWE1ZDctZGE2OWJhMjAyMjVlIiwidXBuIjoiY2hlbnh5QGFydGNoZW4ucGFydG5lci5vbm1zY2hpbmEuY24iLCJwdWlkIjoiMTAwMzMyMzBDNTU2REY2QyIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMzMjMwYzU1NmRmNmNAbGl2ZS5jb20iLCJzY3AiOiJhbGxmaWxlcy53cml0ZSBhbGxwcm9maWxlcy5yZWFkIiwidHQiOiIyIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbH0.MmgyTWljS0tkbFJBeW1qRkR3VDJFSmFYQTNGN282RUFQZE9BS3Vpb0Rvcz0&ApiVersion=2.0
  ROM_NAME: MIUI Q 20.11.15
  TZ: Asia/Kolkata
  MIR: wet
  ZIP_NAME: MIUI Q 20.11.15
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/Velosh/ErfanGSIs-VelanGSIs.git ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z          
       - name: Zip AB and upload 
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
